

    AddProgramOrUnit('BooleanTest', false);
    AddProgramOrUnit('ColorDemo', false);
    AddProgramOrUnit('ErrorHandlingDemo', false);
    AddProgramOrUnit('LongRunningOpDemo', false);
    AddProgramOrUnit('MyApp', false);
    AddProgramOrUnit('MyGit', false);
    AddProgramOrUnit('ProgressDemo', false);
    AddProgramOrUnit('SimpleDemo', false);
    AddProgramOrUnit('SubCommandDemo', false);
    AddProgramOrUnit('TestFlags', false);

